### ISSUE TITLE
从1.0.7更新到1.1.0之后工作不正常

### ISSUE THREAD

**Issue by SnowMoonSS** [cssxsh/weibo-helper#23]
具体表现为：
1、微博订阅内容不推送
2、发送链接后机器人回复`org/apache/commons/text/StringEscapeUtils`
3、添加订阅账户后会正常提示订阅完成并正确显示订阅UID的微博账户名称

```
2021-08-11 12:50:44 V/Bot.xxxxxxxxxxx: xxxxxxxxxx(xxxxxxxxxx) -> https://weibo.com/5648729445/KsWHOcGS4
2021-08-11 12:50:44 I/weibo-helper: [Friend(xxxxxxxxxx)] 匹配WEIBO(KsWHOcGS4)
2021-08-11 12:50:44 W/weibo-helper: java.lang.NoClassDefFoundError: org/apache/commons/text/StringEscapeUtils
java.lang.NoClassDefFoundError: org/apache/commons/text/StringEscapeUtils
        at xyz.cssxsh.mirai.plugin.WeiboUtilsKt$getContent$2.invokeSuspend(WeiboUtils.kt:99)
        at xyz.cssxsh.mirai.plugin.WeiboUtilsKt$getContent$2.invoke(WeiboUtils.kt)
        at xyz.cssxsh.mirai.plugin.WeiboUtilsKt$getContent$2.invoke(WeiboUtils.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
        at kotlinx.coroutines.SupervisorKt.supervisorScope(Supervisor.kt:57)
        at xyz.cssxsh.mirai.plugin.WeiboUtilsKt.getContent(WeiboUtils.kt:88)
        at xyz.cssxsh.mirai.plugin.WeiboUtilsKt.getContent$default(WeiboUtils.kt:88)
        at xyz.cssxsh.mirai.plugin.WeiboUtilsKt.toMessage(WeiboUtils.kt:169)
        at xyz.cssxsh.mirai.plugin.WeiboListener$start$1$1.invokeSuspend(WeiboListener.kt:30)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at xyz.cssxsh.mirai.plugin.WeiboUtilsKt.getContent(WeiboUtils.kt:88)
        at xyz.cssxsh.mirai.plugin.WeiboUtilsKt.getContent$default(WeiboUtils.kt:88)
        at xyz.cssxsh.mirai.plugin.WeiboUtilsKt.toMessage(WeiboUtils.kt:169)
        at xyz.cssxsh.mirai.plugin.WeiboListener$start$1$1.invokeSuspend(WeiboListener.kt:30)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

2021-08-11 12:50:48 I/weibo-helper: 登录成功, LoginResult(result=true, info=LoginUserInfo(display=用户xxxxxxxxxx, uid=xxxxxxxxx))
```

**Comment by cssxsh** [comment]
编译有点问题，之后的版本有解决
