### ISSUE TITLE
安装之后报错，发送/微博登录等无响应  控制台报错java.lang.IllegalStateException: 跳转异常和向 LoginContact 发送消息失败

### ISSUE THREAD

**Issue by kagangtuya-star** [cssxsh/weibo-helper#36]
安装之后报错，发送/微博登录等无响应

```
2022-02-28 13:22:00 W/weibo-helper: WEIBO登陆状态失效，需要重新登陆, java.lang.IllegalStateException: 跳转异常
java.lang.IllegalStateException: 跳转异常
        at xyz.cssxsh.weibo.api.LoginKt.restore(Login.kt:136)
        at xyz.cssxsh.weibo.api.LoginKt$restore$1.invokeSuspend(Login.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

2022-02-28 13:22:00 E/weibo-helper: Exception in coroutine Plugin xyz.cssxsh.mirai.plugin.weibo-helper of weibo-helper
java.util.NoSuchElementException: Not Found LoginContact 12345
        at xyz.cssxsh.mirai.plugin.WeiboUtilsKt$LoginContact$2.invoke(WeiboUtils.kt:146)
        at xyz.cssxsh.mirai.plugin.WeiboUtilsKt$LoginContact$2.invoke(WeiboUtils.kt:141)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at xyz.cssxsh.mirai.plugin.WeiboUtilsKt.getLoginContact(WeiboUtils.kt:141)
        at xyz.cssxsh.mirai.plugin.WeiboUtilsKt$sendLoginMessage$1.invokeSuspend(WeiboUtils.kt:160)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

还偶尔出现这个错误
`2022-02-28 13:34:36 W/weibo-helper: 向 LoginContact 发送消息失败 java.util.NoSuchElementException: Not Found LoginContact 12345`

**Comment by cssxsh** [comment]
`Not Found LoginContact` 你没有设置登录联系人

**Comment by cssxsh** [comment]
执行操作的场景是 ？控制台/群聊/私聊 ？
群聊和私聊可能会有风控导致发不出来的问题

**Comment by kagangtuya-star** [comment]
场景是私聊进行微博登录操作
未存在风控问题，其他插件可正常运作发生消息和图片
https://gitee.com/kagangtuya_light/picbed/raw/master/Snipaste_2022-03-01_13-33-3.png
群聊中出现相同错误

**Comment by cssxsh** [comment]
控制台登录有尝试过吗

**Comment by kagangtuya-star** [comment]
控制台可以正常使用，发送/wlogin 有登录提示回复

而且chat-command和weibo-helper都启用了
`2022-03-02 11:07:32 I/plugin: Successfully loaded plugin Implementation v1.0
2022-03-02 11:07:32 I/plugin: Successfully loaded plugin CaiyunAI v1.0.5
2022-03-02 11:07:32 I/plugin: Successfully loaded plugin Chat Command v0.5.0
2022-03-02 11:07:32 I/plugin: Successfully loaded plugin MCL Addon v1.2.2
2022-03-02 11:07:33 I/plugin: Successfully loaded plugin MiraiNative v2.0.0-beta.1
2022-03-02 11:07:33 I/plugin: Successfully loaded plugin OneBot v0.3.4
2022-03-02 11:07:33 I/plugin: Successfully loaded plugin Tarot v1.0.4
2022-03-02 11:07:33 I/plugin: Successfully loaded plugin weibo-helper v1.4.9`

**Comment by cssxsh** [comment]
> 控制台可以正常使用，发送/wlogin 有登录提示回复
> 
> 而且chat-command和weibo-helper都启用了
> 
> ```
> 2022-03-02 11:07:32 I/plugin: Successfully loaded plugin Implementation v1.0
> 2022-03-02 11:07:32 I/plugin: Successfully loaded plugin CaiyunAI v1.0.5
> 2022-03-02 11:07:32 I/plugin: Successfully loaded plugin Chat Command v0.5.0
> 2022-03-02 11:07:32 I/plugin: Successfully loaded plugin MCL Addon v1.2.2
> 2022-03-02 11:07:33 I/plugin: Successfully loaded plugin MiraiNative v2.0.0-beta.1
> 2022-03-02 11:07:33 I/plugin: Successfully loaded plugin OneBot v0.3.4
> 2022-03-02 11:07:33 I/plugin: Successfully loaded plugin Tarot v1.0.4
> 2022-03-02 11:07:33 I/plugin: Successfully loaded plugin weibo-helper v1.4.9
> ```
> 
> 也成功登录上了，目前可以用命令行来用
> 
> 又出现这个读取失败的错误，我是否应该尝试一下以管理员身份运行？
> 
> ```
> /wuser add 5336331373 915930715
> 对@FF14夜枭in紫水#5336331373的监听任务, 添加完成
> 2022-03-02 11:18:43 I/weibo-helper: 添加对wuser(FF14夜枭in紫水#5336331373)的监听任务
> 2022-03-02 11:18:43 W/weibo-helper: C:\Users\Administrator\Desktop\ff14_bot_dahai\mcl\data\xyz.cssxsh.mirai.plugin.weibo-helper\wuser\5336331373.json 读取失败
> ```

如果是 `保存失败` 才会影响使用  
私聊和群聊应该是触发了风控

**Comment by kagangtuya-star** [comment]
现在可以正常运行了，虽然只能用控制台操作，不过也能使用
仍然是发生指令无没有回复的样子，但控制台一段时间后有回应

2022-03-03 08:44:44 V/Bot.1728518981: [果冻育儿群(879456321456)] 华子(12345678910) -> /blog 5336331373
2022-03-03 08:44:52 V/Bot.1728518981: Event: GroupRecall(bot=Bot(1728518981), authorId=12345678910, messageIds=[87896], messageInternalIds=[431481391], messageTime=1646268253, operator=NormalMember(12345678910), group=Group(879456321456), author=NormalMember(12345678910))
2022-03-03 08:46:59 V/Bot.1728518981: [果冻育儿群(879456321456)] 华子(12345678910) -> /wfollow 5336331373
2022-03-03 08:47:20 V/Bot.1728518981: Event: GroupRecall(bot=Bot(1728518981), authorId=12345678910, messageIds=[87897], messageInternalIds=[821997177], messageTime=1646268388, operator=NormalMember(12345678910), group=Group(879456321456), author=NormalMember(12345678910))

（敏感信息进行了模糊处理）
大概率是风控的问题
