### ISSUE TITLE
org/apache/commons/text/StringEscapeUtils

### ISSUE THREAD

**Issue by SnowMoonSS** [cssxsh/weibo-helper#38]
mirai-core: 2.10.1
mirai-console: 2.10.1
mirai-console-terminal: 2.10.1
weibo-helper: 1.4.12

发送微博链接，后台报错，并在聊天中返回`org/apache/commons/text/StringEscapeUtils`
```
2022-03-10 09:47:41 V/Bot.1234567890: [The Bird's Nest(123456789)] 1234(123456789) -> https://weibo.com/5762457113/Lj3aP5fo2
2022-03-10 09:47:41 I/weibo-helper: Member 123465(123456789.123456789) 匹配WEIBO(Lj3aP5fo2)
2022-03-10 09:47:41 W/weibo-helper: 构建WEIBO(Lj3aP5fo2)信息失败，尝试重新刷新
java.lang.NoClassDefFoundError: org/apache/commons/text/StringEscapeUtils
        at xyz.cssxsh.mirai.plugin.WeiboUtilsKt$getContent$2.invokeSuspend(WeiboUtils.kt:253)
        at xyz.cssxsh.mirai.plugin.WeiboUtilsKt$getContent$2.invoke(WeiboUtils.kt)
        at xyz.cssxsh.mirai.plugin.WeiboUtilsKt$getContent$2.invoke(WeiboUtils.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
        at kotlinx.coroutines.SupervisorKt.supervisorScope(Supervisor.kt:61)
        at xyz.cssxsh.mirai.plugin.WeiboUtilsKt.getContent(WeiboUtils.kt:241)
        at xyz.cssxsh.mirai.plugin.WeiboUtilsKt.toMessage(WeiboUtils.kt:362)
        at xyz.cssxsh.mirai.plugin.WeiboListener$start$1$1.invokeSuspend(WeiboListener.kt:37)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```

**Comment by cssxsh** [comment]
删掉 plugins 文件夹里面的 weibo-helper 让他重新下载

**Comment by SnowMoonSS** [comment]
好，它又行了，感谢诚实守信商会
![BD2`V Y1DLEH739V)Z5VD Y](https://user-images.githubusercontent.com/21017431/157607973-d10d58a3-6fcc-468d-aeef-96fcc3fe001e.jpg)
