### ISSUE TITLE
WEIBO登陆状态失效之后会不断发消息

### ISSUE THREAD

**Issue by SnowMoonSS** [cssxsh/weibo-helper#39]
如题，一直发，一秒好几次的发……
有没有什么办法关掉登录功能，因为经常掉登录，我也不用分组订阅，所以就没登录在用。升级到1.4.12之后又登录了一次，今天掉登录了，就一直给我发消息，删掉`WeiboStatusData.yml`让插件自己重新生成一个之后情况依旧
![L_G~7HA%A1PU2`3JI~M4X{N](https://user-images.githubusercontent.com/21017431/157999389-0d1ff3e5-47b4-423d-b3ec-55cf46beab8d.jpg)

```
2022-03-12 09:45:23 V/Bot.1234567890: Friend(123456789) <- WEIBO登陆状态失效，需要重新登陆 /wlogin
2022-03-12 09:45:23 W/weibo-helper: WEIBO登陆状态失效，需要重新登陆, io.ktor.client.features.ClientRequestException: Client request(https://weibo.com/) invalid: 414 . Text: "<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html>
<head><title>414 Request-URI Too Large</title></head>
<body>
<center><h1>414 Request-URI Too Large</h1></center>
 Sorry for the inconvenience.<br/>
Please report this message and include the following information to us.<br/>
Thank you very much!</p>
<table>
<tr>
<td>URL:</td>
<td>http://weibo.com:8150/</td>
</tr>
<tr>
<td>Server:</td>
<td>mapi-weibopro-node-bypass-7fcfb64cdb-jkv2f</td>
</tr>
<tr>
<td>Date:</td>
<td>2022/03/12 09:45:23</td>
</tr>
</table>
<hr/>Powered by Tengine<hr><center>tengine</center>
</body>
</html>
"
io.ktor.client.features.ClientRequestException: Client request(https://weibo.com/) invalid: 414 . Text: "<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html>
<head><title>414 Request-URI Too Large</title></head>
<body>
<center><h1>414 Request-URI Too Large</h1></center>
 Sorry for the inconvenience.<br/>
Please report this message and include the following information to us.<br/>
Thank you very much!</p>
<table>
<tr>
<td>URL:</td>
<td>http://weibo.com:8150/</td>
</tr>
<tr>
<td>Server:</td>
<td>mapi-weibopro-node-bypass-7fcfb64cdb-jkv2f</td>
</tr>
<tr>
<td>Date:</td>
<td>2022/03/12 09:45:23</td>
</tr>
</table>
<hr/>Powered by Tengine<hr><center>tengine</center>
</body>
</html>
"
        at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invokeSuspend(DefaultResponseValidation.kt:47)
        at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invoke(DefaultResponseValidation.kt)
        at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invoke(DefaultResponseValidation.kt)
        at io.ktor.client.features.HttpCallValidator.validateResponse(HttpCallValidator.kt:54)
        at io.ktor.client.features.HttpCallValidator.access$validateResponse(HttpCallValidator.kt:33)
        at io.ktor.client.features.HttpCallValidator$Companion$install$3.invokeSuspend(HttpCallValidator.kt:133)
        at io.ktor.client.features.HttpCallValidator$Companion$install$3.invoke(HttpCallValidator.kt)
        at io.ktor.client.features.HttpCallValidator$Companion$install$3.invoke(HttpCallValidator.kt)
        at io.ktor.client.features.HttpSend$Feature$install$1.invokeSuspend(HttpSend.kt:96)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by cssxsh** [comment]
不是分组也需要登录才能读取信息的

**Comment by Dream-Rainy** [comment]
主要是登陆失效的信息发的太密集了，一次就是好几条的发。就是能不能把频率调低一点或者把条数改少几条

**Comment by cssxsh** [comment]
with https://github.com/cssxsh/weibo-helper/releases

**Comment by SnowMoonSS** [comment]
一周用下来没有再发生同样的问题了
