### ISSUE TITLE
监听任务序列化时失败

### ISSUE THREAD

**Issue by xianyu1124** [cssxsh/weibo-helper#45]
如图报错，重启服务器重新登录依旧这样
![0](https://user-images.githubusercontent.com/36908318/192491246-a4f60db2-ae3c-4f65-b58c-7cd556549392.png)

**Comment by xianyu1124** [comment]
2022-09-27 17:31:03 W/weibo-helper: wuser(5770760941)监听任务序列化时失败
kotlinx.serialization.MissingFieldException: Fields [quality_label, tcp_receive_buffer] are required for type with serial name 'xyz.cssxsh.weibo.data.PageInfo.MediaInfo.PlayInfo', but they were missing
        at kotlinx.serialization.internal.PluginExceptionsKt.throwMissingFieldException(PluginExceptions.kt:20)
        at weibo-helper-1.5.5.mirai2.jar//xyz.cssxsh.weibo.data.PageInfo$MediaInfo$PlayInfo.<init>(PageInfo.kt:51)
        at weibo-helper-1.5.5.mirai2.jar//xyz.cssxsh.weibo.data.PageInfo$MediaInfo$PlayInfo$$serializer.deserialize(PageInfo.kt:51)
        at weibo-helper-1.5.5.mirai2.jar//xyz.cssxsh.weibo.data.PageInfo$MediaInfo$PlayInfo$$serializer.deserialize(PageInfo.kt:51)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
        at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:51)
        at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:206)
        at kotlinx.serialization.internal.TaggedDecoder$decodeSerializableElement$1.invoke(Tagged.kt:279)
        at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Tagged.kt:296)
        at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableElement(Tagged.kt:279)
        at weibo-helper-1.5.5.mirai2.jar//xyz.cssxsh.weibo.data.PageInfo$MediaInfo$PlayBack$$serializer.deserialize(PageInfo.kt:45)
        at weibo-helper-1.5.5.mirai2.jar//xyz.cssxsh.weibo.data.PageInfo$MediaInfo$PlayBack$$serializer.deserialize(PageInfo.kt:45)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
        at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:51)
        at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:206)
        at kotlinx.serialization.internal.TaggedDecoder$decodeSerializableElement$1.invoke(Tagged.kt:279)
        at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Tagged.kt:296)
        at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableElement(Tagged.kt:279)
        at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:535)
        at kotlinx.serialization.internal.ListLikeSerializer.readElement(CollectionSerializers.kt:80)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:51)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:36)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
        at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:51)
        at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:206)
        at kotlinx.serialization.internal.TaggedDecoder$decodeSerializableElement$1.invoke(Tagged.kt:279)
        at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Tagged.kt:296)
        at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableElement(Tagged.kt:279)
        at weibo-helper-1.5.5.mirai2.jar//xyz.cssxsh.weibo.data.PageInfo$MediaInfo$$serializer.deserialize(PageInfo.kt:21)
        at weibo-helper-1.5.5.mirai2.jar//xyz.cssxsh.weibo.data.PageInfo$MediaInfo$$serializer.deserialize(PageInfo.kt:21)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
        at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:51)
        at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:206)
        at kotlinx.serialization.internal.TaggedDecoder$decodeNullableSerializableElement$1.invoke(Tagged.kt:288)
        at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Tagged.kt:296)
        at kotlinx.serialization.internal.TaggedDecoder.decodeNullableSerializableElement(Tagged.kt:287)
        at weibo-helper-1.5.5.mirai2.jar//xyz.cssxsh.weibo.data.PageInfo$$serializer.deserialize(PageInfo.kt:5)
        at weibo-helper-1.5.5.mirai2.jar//xyz.cssxsh.weibo.data.PageInfo$$serializer.deserialize(PageInfo.kt:5)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
        at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:51)
        at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:206)
        at kotlinx.serialization.internal.TaggedDecoder$decodeNullableSerializableElement$1.invoke(Tagged.kt:288)
        at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Tagged.kt:296)
        at kotlinx.serialization.internal.TaggedDecoder.decodeNullableSerializableElement(Tagged.kt:287)
        at weibo-helper-1.5.5.mirai2.jar//xyz.cssxsh.weibo.data.MicroBlog$$serializer.deserialize(MicroBlog.kt:13)
        at weibo-helper-1.5.5.mirai2.jar//xyz.cssxsh.weibo.data.MicroBlog$$serializer.deserialize(MicroBlog.kt:13)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
        at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:51)
        at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:206)
        at kotlinx.serialization.internal.TaggedDecoder$decodeSerializableElement$1.invoke(Tagged.kt:279)
        at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Tagged.kt:296)
        at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableElement(Tagged.kt:279)
        at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:535)
        at kotlinx.serialization.internal.ListLikeSerializer.readElement(CollectionSerializers.kt:80)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:51)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:36)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
        at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:51)
        at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:206)
        at kotlinx.serialization.internal.TaggedDecoder$decodeSerializableElement$1.invoke(Tagged.kt:279)
        at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Tagged.kt:296)
        at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableElement(Tagged.kt:279)
        at weibo-helper-1.5.5.mirai2.jar//xyz.cssxsh.weibo.data.UserBlog$$serializer.deserialize(MicroBlog.kt:125)
        at weibo-helper-1.5.5.mirai2.jar//xyz.cssxsh.weibo.data.UserBlog$$serializer.deserialize(MicroBlog.kt:125)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
        at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:51)
        at kotlinx.serialization.json.internal.TreeJsonDecoderKt.readJson(TreeJsonDecoder.kt:24)
        at kotlinx.serialization.json.Json.decodeFromJsonElement(Json.kt:119)
        at weibo-helper-1.5.5.mirai2.jar//xyz.cssxsh.weibo.api.StatusesKt.getUserMicroBlogs(Statuses.kt:135)
        at weibo-helper-1.5.5.mirai2.jar//xyz.cssxsh.weibo.api.StatusesKt$getUserMicroBlogs$1.invokeSuspend(Statuses.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at weibo-helper-1.5.5.mirai2.jar[private]//io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
        at weibo-helper-1.5.5.mirai2.jar[private]//io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
        at weibo-helper-1.5.5.mirai2.jar[private]//io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
        at weibo-helper-1.5.5.mirai2.jar[private]//io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at weibo-helper-1.5.5.mirai2.jar[private]//io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
        at weibo-helper-1.5.5.mirai2.jar[private]//io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
        at weibo-helper-1.5.5.mirai2.jar[private]//io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
        at weibo-helper-1.5.5.mirai2.jar[private]//io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at weibo-helper-1.5.5.mirai2.jar[private]//io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
        at weibo-helper-1.5.5.mirai2.jar[private]//io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
        at weibo-helper-1.5.5.mirai2.jar[private]//io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
        at weibo-helper-1.5.5.mirai2.jar[private]//io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at weibo-helper-1.5.5.mirai2.jar[private]//io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
        at weibo-helper-1.5.5.mirai2.jar[private]//io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
        at weibo-helper-1.5.5.mirai2.jar[private]//io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
        at weibo-helper-1.5.5.mirai2.jar[private]//io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

**Comment by NiGuangOwO** [comment]
+1 下午17:18开始报错

**Comment by SnowMoonSS** [comment]
试了最新版，已经不会出现这个问题了

**Comment by cssxsh** [comment]
@NiGuangOwO 
@xianyu1124 
请升级最新版
