### ISSUE TITLE
微博状态刷新

### ISSUE THREAD

**Issue by xianyu1124** [cssxsh/weibo-helper#46]
```
2023-03-07 11:08:39 W/weibo-helper: WEIBO登陆状态将刷新
io.ktor.client.plugins.ServerResponseException: Server error(GET https://weibo.com/ajax/statuses/mymblog?uid=6441489862&page=1&feature=0: 504 . Text: "<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
 Sorry for the inconvenience.<br/>
Please report this message and include the following information to us.<br/>
Thank you very much!</p>
<table>
<tr>
<td>URL:</td>
<td>https://weibo.com:1443/ajax/statuses/mymblog?uid=6441489862&amp;page=1&amp;feature=0</td>
</tr>
<tr>
<td>Server:</td>
<td>mweibo-sslv6-003.tc.intra.weibo.cn</td>
</tr>
<tr>
<td>Date:</td>
<td>2023/03/07 11:08:31</td>
</tr>
</table>
<hr/>Powered by WBGW<hr><center>tengine</center>
</body>
</html>
"
        at weibo-helper-1.6.1.mirai2.jar[private]//io.ktor.client.plugins.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invokeSuspend(DefaultResponseValidation.kt:55)
        at weibo-helper-1.6.1.mirai2.jar[private]//io.ktor.client.plugins.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invoke(DefaultResponseValidation.kt)
        at weibo-helper-1.6.1.mirai2.jar[private]//io.ktor.client.plugins.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invoke(DefaultResponseValidation.kt)
        at weibo-helper-1.6.1.mirai2.jar[private]//io.ktor.client.plugins.HttpCallValidator.validateResponse(HttpCallValidator.kt:51)
        at weibo-helper-1.6.1.mirai2.jar[private]//io.ktor.client.plugins.HttpCallValidator.access$validateResponse(HttpCallValidator.kt:43)
        at weibo-helper-1.6.1.mirai2.jar[private]//io.ktor.client.plugins.HttpCallValidator$Companion$install$3.invokeSuspend(HttpCallValidator.kt:152)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by cssxsh** [comment]
`504 Gateway Time-out`
网络波动

或者你需要重新登录一下微博账号

**Comment by cssxsh** [comment]
关掉 mirai 然后删掉 `data/xyz.cssxsh.mirai.plugin.weibo-helper/WeiboStatusData.yml` 
完全重置登录状态
