### ISSUE TITLE
群聊/私聊均无法成功发送微博视频

### ISSUE THREAD

**Issue by SisCleaire** [cssxsh/weibo-helper#48]
群聊如下
`22023-05-07 12:44:52 V/Bot.: [] 45510号爱学长() -> https://m.weibo.cn/2634877355/4898345347191555
2023-05-07 12:44:52 I/weibo-helper: Member 45510号爱学长() 匹配WEIBO(4898345347191555)
2023-05-07 12:44:53 W/weibo-helper: Group() 无法发送文件
java.lang.IllegalStateException: Failed AbsoluteFolderImpl.upload, result=-403, msg=group space not enough
        at net.mamoe.mirai.internal.contact.file.CommonAbsoluteFolderImpl$Companion.uploadNewFileImpl(AbsoluteFolderImpl.kt:157)
        at net.mamoe.mirai.internal.contact.file.CommonAbsoluteFolderImpl$Companion$uploadNewFileImpl$1.invokeSuspend(AbsoluteFolderImpl.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)`

私聊如下
`2023-05-07 12:45:43 I/weibo-helper: Friend 楽しい() 匹配WEIBO(4898345347191555)
2023-05-07 12:45:43 V/Bot.: 楽しい() -> https://m.weibo.cn/2634877355/4898345347191555
2023-05-07 12:45:43 W/weibo-helper: Friend() 无法发送文件
java.lang.ClassCastException: class net.mamoe.mirai.internal.contact.FriendImpl cannot be cast to class net.mamoe.mirai.contact.FileSupported (net.mamoe.mirai.internal.contact.FriendImpl and net.mamoe.mirai.contact.FileSupported are in unnamed module of loader 'app')
        at weibo-helper-1.6.2.mirai2.jar//xyz.cssxsh.mirai.weibo.WeiboUtilsKt$toMessage$2$3$1.invokeSuspend(WeiboUtils.kt:366)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)`

**Comment by cssxsh** [comment]
1.  mirai 不支持私聊文件
2.  `msg=group space not enough` 自行检查群群文件空间是否已满

**Comment by SisCleaire** [comment]
可以实现在群空间已满的情况下发送视频吗

**Comment by cssxsh** [comment]
> 可以实现在群空间已满的情况下发送视频吗

不行，mirai 还没有实现视频上传
