### ISSUE TITLE
微博视频文件无法发送

### ISSUE THREAD

**Issue by onlyzqy** [cssxsh/weibo-helper#50]
```
2023-09-11 13:40:35 W/weibo-helper: Group(746438576) 无法发送文件
io.ktor.client.plugins.ClientRequestException: Client request(GET http://f.video.weibocdn.com/o0/QuiCcv75lx088w3LPwCk01041200oTtg0E010.mp4?label=mp4_1080p&template=1080x1920.24.0&media_id=4944764617818163&tp=8x8A3El:YTkl0eM8&us=0&ori=1&bf=4&ot=v&lp=000028lAnx&ps=mZ6WB&uid=zq1FFq7&ab=11243-g2,8012-g2,8143-g0,8013-g0,3601-g29&Expires=1694414435&ssig=N7UGwuf%2BUN&KID=unistore,video) invalid: 403 Forbidden. Text: "<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>openresty</center>
</body>
</html>
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
"
        at weibo-helper-1.6.2.mirai2.jar[private]//io.ktor.client.plugins.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invokeSuspend(DefaultResponseValidation.kt:54)
        at weibo-helper-1.6.2.mirai2.jar[private]//io.ktor.client.plugins.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invoke(DefaultResponseValidation.kt)
        at weibo-helper-1.6.2.mirai2.jar[private]//io.ktor.client.plugins.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invoke(DefaultResponseValidation.kt)
        at weibo-helper-1.6.2.mirai2.jar[private]//io.ktor.client.plugins.HttpCallValidator.validateResponse(HttpCallValidator.kt:51)
        at weibo-helper-1.6.2.mirai2.jar[private]//io.ktor.client.plugins.HttpCallValidator.access$validateResponse(HttpCallValidator.kt:43)
        at weibo-helper-1.6.2.mirai2.jar[private]//io.ktor.client.plugins.HttpCallValidator$Companion$install$3.invokeSuspend(HttpCallValidator.kt:152)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```
日志内容如上，群文件空间未满

**Comment by cssxsh** [comment]
你们提交日志为什么不格式化一下呢
帮你处理了
